---
title: "Lecture 20"
author: "Charlie Struhs"
date: "2024-11-18"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Confidence Intervals for differences in means

```{r}
library(tidyverse)
library(infer)
library(ps270data)
trains
```

Estimating the differences in means

```{r}
diff_in_means <- trains |>
  group_by(treatment) |>
  summarize(post_mean = mean(numberim.post)) |>
pivot_wider(names_from = treatment, values_from = post_mean) |>
  mutate(ATE = `1` - `0`)
diff_in_means
```


Bootstrap for the differences in means

```{r}
dim_boots <- trains |>
  rep_slice_sample(prop = 1, replace = TRUE, reps = 1000) |>
  group_by(replicate, treatment) |>
  summarize(post_mean = mean(numberim.post)) |>
pivot_wider(names_from = treatment, values_from = post_mean) |>
  mutate(ATE = `1` - `0`)
dim_boots

```
visualize the bootstraps

```{r}
dim_boots |>
  ggplot(aes(x = ATE)) + 
  geom_histogram(aes(y = after_stat(density)), binwidth = 0.05)
```

calculating the percentile CI

```{r}
dim_ci_95 <- dim_boots |>
  select(replicate, ATE) |>
  get_confidence_interval(level = 0.95, type = "percentile")
dim_ci_95
```

What about change in views as the outcome?

```{r}
change_ci_95 <- trains |>
  rep_slice_sample(prop = 1, replace = TRUE, reps = 1000) |>
  group_by(replicate, treatment) |>
  summarize(change_mean = mean(numberim.post - numberim.pre)) |>
  pivot_wider(names_from = treatment, values_from = change_mean) |>
  mutate(ATE = `1`-`0`) |>
select(replicate, ATE) |>
  get_confidence_interval(level = 0.95, type = "percentile")
change_ci_95
```


lets compare the width of the two confidence intervals

```{r}
dim_ci_95[2] - dim_ci_95[1]
```

the second one

```{r}
change_ci_95[2] - change_ci_95[1]
```

